name: My First Workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: welcome message
              run: echo "My first github Actions Job"
            
            - name: Checkout
              uses: actions/checkout@v4

            - name: List files
              run: ls
            
            - name: Read file
              run: cat README.md