name: Docker Build and Deploy

on: push

env:
  DOCKER_USERNAME: Dhananjaykulkarni
  DOCKER_PASSWORD: <Password>
  IMAGE_NAME: your-image-name                    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        run: echo $DOCKER_PASSWORD | echo docker login -u $DOCKER_USERNAME --password-stdin

      - name: Docker Push
        run: echo docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Docker Login
        run: echo $DOCKER_PASSWORD | echo docker login -u $DOCKER_USERNAME --password-stdin

      - name: Docker Pull
        run: echo docker pull $DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Run
        run: echo docker run -d --name my-app -p 80:80 $DOCKER_USERNAME/$IMAGE_NAME:latest
